### ISSUE TITLE
importClause might be null

### ISSUE THREAD

**Issue by ljani** [longlho/ts-transform-css-modules#5]
[`ts-transform-css-modules`](https://github.com/longlho/ts-transform-css-modules) fails parsing the following `example.ts` file:

```js
import "styles.css";
```

The reason for this seems to be that there is no [`importClause`](https://github.com/longlho/ts-transform-css-modules/blob/70b6f080808e5b2ae77497a75f29bc896c8b5a1e/src/transform.ts#L68) in this case.

The actual error is:

```
[at-loader]: Child process failed to process the request:  TypeError: Cannot match against 'undefined' or 'null'.
    at importVisitor (<snip>\node_modules\ts-transform-css-modules\dist\transform.js:38:35)
    at visitor (<snip>\node_modules\ts-transform-css-modules\dist\transform.js:76:28)
    at visitNodes (<snip>\node_modules\typescript\lib\typescript.js:49280:48)
    at visitLexicalEnvironment (<snip>\node_modules\typescript\lib\typescript.js:49313:22)
    at Object.visitEachChild (<snip>\node_modules\typescript\lib\typescript.js:49605:54)
    at visitor (<snip>\node_modules\ts-transform-css-modules\dist\transform.js:90:19)
    at Object.visitNode (<snip>\node_modules\typescript\lib\typescript.js:49229:23)
    at <snip>\node_modules\ts-transform-css-modules\dist\transform.js:97:27
    at <snip>\node_modules\typescript\lib\typescript.js:2492:86
<snip>
```

**Comment by longlho** [comment]
hmm what's ur use case? The primary supported use case is to inline the class names in (check out README), but since ur not using the classnames do u want to just create an explicit dependency btwn ur `ts` & `css`?

**Comment by ljani** [comment]
I'm using `styles.css` to include a few globals in my entrypoint. For example:

```css
:global(html) {
    background: #fff;
}
```

IMO [`ts-transform-css-modules`](https://github.com/longlho/ts-transform-css-modules) should just skip this file instead of crashing with an error.

**Comment by longlho** [comment]
ah gotcha yeah that's possible. I'll try to fix it tonite or you can beat me to it w/ a PR :)
